// Application context
export const CHANGE_APP_STATE = 'CHANGE_APP_STATE';

// Students
export const CHANGE_STUDENT_FILTER = 'CHANGE_STUDENT_FILTER';

export const SELECT_STUDENT_FROMDATE = 'SELECT_STUDENT_FROMDATE';
export const SELECT_STUDENT_TODATE = 'SELECT_STUDENT_TODATE';

export const STUDENTS_REQUEST = 'STUDENTS_REQUEST';
export const STUDENTS_RECEIVE = 'STUDENTS_RECEIVE';
export const SELECT_STUDENT = 'SELECT_STUDENT';

export const GROUPS_REQUEST = 'GROUPS_REQUEST';
export const GROUPS_RECEIVE = 'GROUPS_RECEIVE';

export const FACULTIES_REQUEST = 'FACULTIES_REQUEST';
export const FACULTIES_RECEIVE = 'FACULTIES_RECEIVE';

export const INSTITUTES_REQUEST = 'INSTITUTES_REQUEST';
export const INSTITUTES_RECEIVE = 'INSTITUTES_RECEIVE';

export const STUDENT_DISCIPLINE_WORKLOAD_REQUEST = 'STUDENT_DISCIPLINE_WORKLOAD_REQUEST';
export const STUDENT_DISCIPLINE_WORKLOAD_RECEIVE = 'STUDENT_DISCIPLINE_WORKLOAD_RECEIVE';

// Lecturers
export const CHANGE_LECTURER_FILTER = 'CHANGE_LECTURER_FILTER';
export const CHAIRS_REQUEST = 'CHAIRS_REQUEST';
export const CHAIRS_RECEIVE = 'CHAIRS_RECEIVE';

export const SELECT_LECTURER_FROMDATE = 'SELECT_LECTURER_FROMDATE';
export const SELECT_LECTURER_TODATE = 'SELECT_LECTURER_TODATE';
export const SELECT_LECTURER = 'SELECT_LECTURER';

export const LECTURERS_REQUEST = 'LECTURERS_REQUEST';
export const LECTURERS_RECEIVE = 'LECTURERS_RECEIVE';

export const LECTURER_DISCIPLINE_WORKLOAD_REQUEST = 'LECTURER_DISCIPLINE_WORKLOAD_REQUEST';
export const LECTURER_DISCIPLINE_WORKLOAD_RECEIVE = 'LECTURER_DISCIPLINE_WORKLOAD_RECEIVE';

// Department
export const DEPARTMENT_WORKLOAD_REQUEST = 'DEPARTMENT_WORKLOAD_REQUEST';
export const DEPARTMENT_WORKLOAD_RECEIVE = 'DEPARTMENT_WORKLOAD_RECEIVE';

export const CHANGE_DEPARTMENT_FILTER = 'CHANGE_DEPARTMENT_FILTER';

export const CHANGE_DEPARTMENT_TABLE_FILTER = 'CHANGE_DEPARTMENT_TABLE_FILTER';
export const UPDATE_DEPARTMENT_WORKLOAD = 'UPDATE_DEPARTMENT_WORKLOAD';